### ISSUE TITLE
where is the valid_dataset?

### ISSUE THREAD

**Issue by weizhiliang0520** [Saafke/EDSR_Tensorflow#5]
Hi! I have the last problem, I can't find the valid dataset, could you please tell me, how working when running the train code?
Thanks!

**Comment by Saafke** [comment]
Hi,

You can download the validation set from this website link: https://data.vision.ee.ethz.ch/cvl/DIV2K/ 
You can scroll down to see the link **Validation Data (HR images)** under High Resolution Images

Then you pass the path the folder as an argument when wanting to train, for example:

`python main.py --train --validdir <insert-here-your-path-to-validation-set>`
