### ISSUE TITLE
About the mean rgb of DIV2K dataset

### ISSUE THREAD

**Issue by johnniewalker3** [Saafke/EDSR_Tensorflow#8]
Hello my friend,
Your project is so helpful.i have got many ideas from the way you have written it.I would want to ask you some questions.When we find the  mean rgb value of div2k dataset , are we using the Low resolution images of train dataset(800 images) or are we using the low resolution images of train,validation and testing to find the mean rgb value(all the low resolution images of the dataset)?This mean value is this value we must subtract from our data when we pass them in the network

**Comment by Saafke** [comment]
Hi Johnnie,

When you calculate the mean you always only use the **training** dataset (otherwise it's 'cheating').

**Comment by johnniewalker3** [comment]
Thanks for the soon answer.Also I noticed you are using the mean value of high resolution training dataset.we can use either low resolution or high resolution training dataset to calculate mean RGB value because their difference is very small.I had made a program to check this before  continue to the next step which was the creation of the network and after this the training step
